name: Check DApp Examples with yarn audit

on:
  push:
    branches: 
      - main
      - COR-2064/yarn-audit-slack

  schedule:
      - cron: '0 12 * * *' # run every day at 12
  # Allows us to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  yarn-audit:
    name: Yarn Audit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        packages:
          - dapp-template/frontend
          - euroe-demo
          - gallery
          - low-code-nft-marketplace
          - signMessage
          - simpleAgeVerification
          - sponsoredTransactions/frontend
          - sponsoredTransactionsAuction/frontend
          - trackAndTrace/frontend
          - testnet-faucet
          - compliant-reward-distribution/frontend
          - nft-minting
          - piggybank
          - eSealing
          - voting
          - wCCD

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: ${{ matrix.packages }}/yarn.lock

      - name: Install Dependencies
        working-directory: ${{ matrix.packages }}
        run: yarn install --immutable

      - name: Audit - Critical vulnerabilities
        id: audit_critical
        working-directory: ${{ matrix.packages }}
        run: |
          AUDIT_OUTPUT=$(yarn npm audit --all --recursive --severity critical || true)
          echo "$AUDIT_OUTPUT"
          if echo "$AUDIT_OUTPUT" | grep -Ei "severity: critical" > /dev/null; then
            echo "Critical vulnerabilities found!"
            exit 1
          else
            echo "No critical vulnerabilities found."
            exit 0
          fi

      - name: Audit - High vulnerabilities
        id: audit_high
        working-directory: ${{ matrix.packages }}
        run: |
          AUDIT_OUTPUT=$(yarn npm audit --all --recursive --severity high || true)
          echo "$AUDIT_OUTPUT"
          if echo "$AUDIT_OUTPUT" | grep -Ei "severity: high" > /dev/null; then
            echo "High vulnerabilities found!"
            exit 1
          else
            echo "No high vulnerabilities found."
            exit 0
          fi

      - name: Report Status to Slack # This step only runs if a previous step failed
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SECURITY_ADVISORIES_SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'Yarn Audit detected vulnerabilities on : ${{ matrix.packages }}'
          SLACK_MESSAGE: |
            Yarn audit detected Critical or High vulnerabilities for *${{ matrix.packages }}*. 
            Please check the GitHub Actions logs.
            *View Logs:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here to open the Summary page>
          SLACK_USERNAME: YarnAuditBot
